// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: favoriteService.proto

package favoritePb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FavoriteService service

func NewFavoriteServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FavoriteService service

type FavoriteService interface {
	FavoriteAction(ctx context.Context, in *FavoriteActionRequest, opts ...client.CallOption) (*FavoriteActionResponse, error)
	FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...client.CallOption) (*FavoriteListResponse, error)
}

type favoriteService struct {
	c    client.Client
	name string
}

func NewFavoriteService(name string, c client.Client) FavoriteService {
	return &favoriteService{
		c:    c,
		name: name,
	}
}

func (c *favoriteService) FavoriteAction(ctx context.Context, in *FavoriteActionRequest, opts ...client.CallOption) (*FavoriteActionResponse, error) {
	req := c.c.NewRequest(c.name, "FavoriteService.FavoriteAction", in)
	out := new(FavoriteActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...client.CallOption) (*FavoriteListResponse, error) {
	req := c.c.NewRequest(c.name, "FavoriteService.FavoriteList", in)
	out := new(FavoriteListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FavoriteService service

type FavoriteServiceHandler interface {
	FavoriteAction(context.Context, *FavoriteActionRequest, *FavoriteActionResponse) error
	FavoriteList(context.Context, *FavoriteListRequest, *FavoriteListResponse) error
}

func RegisterFavoriteServiceHandler(s server.Server, hdlr FavoriteServiceHandler, opts ...server.HandlerOption) error {
	type favoriteService interface {
		FavoriteAction(ctx context.Context, in *FavoriteActionRequest, out *FavoriteActionResponse) error
		FavoriteList(ctx context.Context, in *FavoriteListRequest, out *FavoriteListResponse) error
	}
	type FavoriteService struct {
		favoriteService
	}
	h := &favoriteServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FavoriteService{h}, opts...))
}

type favoriteServiceHandler struct {
	FavoriteServiceHandler
}

func (h *favoriteServiceHandler) FavoriteAction(ctx context.Context, in *FavoriteActionRequest, out *FavoriteActionResponse) error {
	return h.FavoriteServiceHandler.FavoriteAction(ctx, in, out)
}

func (h *favoriteServiceHandler) FavoriteList(ctx context.Context, in *FavoriteListRequest, out *FavoriteListResponse) error {
	return h.FavoriteServiceHandler.FavoriteList(ctx, in, out)
}
