name: CI

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get -y install autoconf automake build-essential libass-dev libfreetype6-dev libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev pkg-config texi2html zlib1g-dev
          sudo apt install -y libavdevice-dev libavfilter-dev libswscale-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev
          sudo apt-get install yasm
          export FFMPEG_ROOT=$HOME/ffmpeg
          export CGO_LDFLAGS="-L$FFMPEG_ROOT/lib/ -lavcodec -lavformat -lavutil -lswscale -lswresample -lavdevice -lavfilter"
          export CGO_CFLAGS="-I$FFMPEG_ROOT/include"
          export LD_LIBRARY_PATH=$HOME/ffmpeg/lib

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

  semantic-release:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Run semantic-release
        if: github.repository == 'UESTCByteDance/ByteRhythm' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
